'''
DATASET PATHS
'''

ARTIFACT_DIR = 'Artifacts'

TRAIN_IMAGE_DIR = 'dataset/train/images'
TRAIN_ANNOTATION_DIR = 'dataset/train/annotations'

TEST_IMAGE_DIR = 'dataset/test/images'
TEST_ANNOTATION_DIR = 'dataset/test/annotations'

VAL_IMAGE_DIR = 'dataset/val/images'
VAL_ANNOTATION_DIR = 'dataset/val/annotations'

BATCH_SIZE = 24

CLASSES = ['person']


IMAGE_CHANNELS = 3
MIN_IMAGE_SIZE = 600
MAX_IMAGE_SIZE = 1000
IMAGE_MEAN = [0.485, 0.456, 0.406]
IMAGE_STANDARD_DEVIATION = [0.229, 0.224, 0.225]


RPN_BACKBONE_OUT_CHANNELS = 512
RPN_ASPECT_RATIOS = [0.5, 1, 2]
RPN_SCALES = [128, 256, 512]
RPN_BACKGROUND_THRESHOLD = 0.3
RPN_FOREGROUND_THRESHOLD = 0.7
RPN_NMS_THRESHOLD = 0.7
RPN_TRAIN_PRENMS_TOPK = 12000
RPN_TEST_PRENMS_TOPK = 6000
RPN_TRAIN_TOPK = 2000
RPN_TEST_TOPK = 300
RPN_BATCH_SIZE = 256
RPN_POS_FRACTION = 0.5

ROI_BACKBONE_OUT_CHANNELS = 512
ROI_IOU_THRESHOLD = 0.5
ROI_LOW_BG_IOU = 0.0
ROI_POOL_SIZE = 7
ROI_NMS_THRESHOLD = 0.3
ROI_TOPK_DETECTION = 100
ROI_SCORE_THRESHOLD = 0.05
ROI_BATCH_SIZE = 128
ROI_POS_FRACTION = 0.25
ROI_FC_INNER_DIM = 1024

TASK_NAME:str = 'person_detection'
SEED = 1111
ACC_STEPS = 1
EPOCHS = 20
LR_STEPS = [12, 16]
LR = 0.001
CKPT_NAME = 'best'



